
[functions.get-unipile-key]
enabled = true
verify_jwt = true
import_map = "./functions/get-unipile-key/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/get-unipile-key/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/get-unipile-key/*.html" ]

[functions.unipile-webhook]
enabled = true
verify_jwt = true
import_map = "./functions/unipile-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/unipile-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/unipile-webhook/*.html" ]
